group 'com.travelunion.flutter_biometrics'
version '1.0-SNAPSHOT'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

plugins {
    id 'com.android.library'
}

android {
    compileSdkVersion 34

    defaultConfig {
        minSdkVersion 23
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}

dependencies {
    implementation 'androidx.biometric:biometric:1.2.0'
    implementation 'androidx.core:core:1.9.0'
    implementation 'androidx.fragment:fragment:1.5.7'
}
